import os
print(os.getcwd())
print(os.getcwdb())
#os.chdir('/home')
print(os.getcwd())
print(os.listdir())
#os.mkdir('Demo_Dir')
print(os.listdir())
#os.rename('Demo_Dir','DemoDir')
print(os.listdir())
os.removedirs('DemoDir')
print(os.listdir())